# Generated by Django 2.1.15 on 2020-05-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
